# Generated by Django 3.1 on 2020-08-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gardens',
            new_name='Garden',
        ),
    ]
