# Generated by Django 3.1 on 2020-08-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='garden_id',
            new_name='garden',
        ),
        migrations.RenameField(
            model_name='garden',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='plantvariety',
            old_name='plant_id',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='bed_id',
            new_name='bed',
        ),
    ]
