# Generated by Django 3.1 on 2020-08-16 19:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200816_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 16, 19, 13, 19, 728492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='garden',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 16, 19, 13, 19, 728027, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='plant',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 16, 19, 13, 19, 729495, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='plantvariety',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 16, 19, 13, 19, 729960, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='section',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 16, 19, 13, 19, 728953, tzinfo=utc)),
        ),
    ]
