# Generated by Django 3.1 on 2020-08-19 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200816_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='user',
        ),
        migrations.AddField(
            model_name='garden',
            name='posted_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to=settings.AUTH_USER_MODEL),
        ),
    ]
