# Generated by Django 3.1 on 2020-08-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_garden_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garden',
            old_name='gardenName',
            new_name='garden_name',
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('length', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.CharField(max_length=500)),
                ('garden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garden')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
