# Generated by Django 3.1 on 2020-08-15 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200815_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garden',
            old_name='owner',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='bed',
            name='garden_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='api.garden'),
        ),
    ]
