# Generated by Django 3.1 on 2020-08-16 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200815_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('xLocation', models.PositiveSmallIntegerField(default=0)),
                ('yLocation', models.PositiveSmallIntegerField(default=0)),
                ('bed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.bed')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
