# Generated by Django 3.1 on 2020-09-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beds", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bed",
            old_name="name",
            new_name="bed_name",
        ),
    ]
