# Generated by Django 3.1 on 2020-10-04 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_beds', to=settings.AUTH_USER_MODEL),
        ),
    ]
