# Generated by Django 3.1 on 2020-10-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_remove_garden_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='name',
            field=models.CharField(default='defaultName', max_length=100),
            preserve_default=False,
        ),
    ]
