# Generated by Django 3.1 on 2020-10-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='name',
        ),
    ]
