# Generated by Django 3.1 on 2020-10-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_garden_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
