# Generated by Django 3.1 on 2020-10-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_bed_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='description',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
