# Generated by Django 3.1 on 2020-09-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="name",
        ),
    ]
